changelog:
  exclude:
    labels: [skip-changelog]
  categories:
    - title: Features
      labels: [enhancement, token-support, mca-forms, gui]
    - title: Fixes
      labels: [bug]
    - title: Security
      labels: [security]
    - title: Docs
      labels: [docs]
    - title: Packaging
      labels: [packaging]
    - title: Dependencies
      labels: [dependencies]
    - title: Other changes
      labels: ["*"]
