#!/usr/bin/env python3
# Add InnaitKey DSC (338c:0031) to the CCID driver device list. Idempotent. Edits a file owned by the ccid package.
import re, sys
P = "/usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist"
t = open(P).read()
if "0x338C" in t:
    sys.exit(0)
for key, val in (("ifdVendorID", "0x338C"), ("ifdProductID", "0x0031"), ("ifdFriendlyName", "InnaitKey DSC")):
    t, n = re.subn(r"(<key>%s</key>\s*<array>.*?)(\s*</array>)" % key,
                   lambda m: m.group(1) + "\n\t\t<string>%s</string>" % val + m.group(2), t, count=1, flags=re.S)
    assert n == 1, key
open(P, "w").write(t)
